title: AnkiLingoFlash
description: Master Languages Faster with AI-Powered Flashcards
baseurl: ""
url: ""

theme: just-the-docs

color_scheme: custom
search_enabled: false
heading_anchors: true

aux_links: {}

footer_content: "© 2024 AnkiLingoFlash. All rights reserved."

collections:
  getting-started:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: getting-started
    values:
      layout: page

nav_external_links: []

# Commentez ou supprimez cette section
nav_order:
   - Home
   - Getting Started
   - Blog
#   - About

just_the_docs:
  gh_edit_link: false

includes:
  - custom.css