title: AnkiLingoFlash<span class="site-logo"></span>
description: Master Languages Faster with AI-Powered Flashcards
baseurl: ""
url: ""

remote_theme: just-the-docs/just-the-docs

color_scheme: custom
search_enabled: false
heading_anchors: true

aux_links: {}

footer_content: "© 2024 AnkiLingoFlash. All rights reserved."

collections:
  getting-started:
    output: true
    permalink: /:collection/:path/
 
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: getting-started
    values:
      layout: page

nav_external_links: []

nav_order:
   - "1. Home"
   - "2. Getting Started"
   - "3. Installation"
   - "4. Quick Tutorial"
   - "5. Blog"
   - About

plugins:
  - jekyll-remote-theme

includes:
  - custom.css

sass:
  sass_dir: _sass
  style: compressed